# Generated by Django 4.1 on 2022-08-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
                ('category_image', models.CharField(max_length=200)),
                ('category_icon', models.CharField(max_length=200)),
                ('word', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('word_image', models.CharField(max_length=200)),
                ('word_audioSrc', models.CharField(max_length=200)),
            ],
        ),
    ]
